// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhObRVa_Ru7e1C30SRnRJ4-qD6HaEBnLY',
    appId: '1:351281836507:web:e7e9271cc731ca246637fe',
    messagingSenderId: '351281836507',
    projectId: 'futsalapp-f2c9f',
    authDomain: 'futsalapp-f2c9f.firebaseapp.com',
    storageBucket: 'futsalapp-f2c9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWrYACcVSQDk4UM39UUaMDmaYNHClZgyg',
    appId: '1:351281836507:android:834e74023470fa256637fe',
    messagingSenderId: '351281836507',
    projectId: 'futsalapp-f2c9f',
    storageBucket: 'futsalapp-f2c9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpMSsiwbxtK7MSXrK8QunJ51NKS_OgIkI',
    appId: '1:351281836507:ios:43e853d26148d3d76637fe',
    messagingSenderId: '351281836507',
    projectId: 'futsalapp-f2c9f',
    storageBucket: 'futsalapp-f2c9f.firebasestorage.app',
    iosBundleId: 'com.example.futsalapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpMSsiwbxtK7MSXrK8QunJ51NKS_OgIkI',
    appId: '1:351281836507:ios:43e853d26148d3d76637fe',
    messagingSenderId: '351281836507',
    projectId: 'futsalapp-f2c9f',
    storageBucket: 'futsalapp-f2c9f.firebasestorage.app',
    iosBundleId: 'com.example.futsalapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhObRVa_Ru7e1C30SRnRJ4-qD6HaEBnLY',
    appId: '1:351281836507:web:b4bae22b6ea44ee96637fe',
    messagingSenderId: '351281836507',
    projectId: 'futsalapp-f2c9f',
    authDomain: 'futsalapp-f2c9f.firebaseapp.com',
    storageBucket: 'futsalapp-f2c9f.firebasestorage.app',
  );
}
