// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFaGOtVhLwB_Qimgzd1_zgd1jOU2ai4YY',
    appId: '1:353926578262:web:29fd506dfd074b4e4c7bf7',
    messagingSenderId: '353926578262',
    projectId: 'football-afe29',
    authDomain: 'football-afe29.firebaseapp.com',
    storageBucket: 'football-afe29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfh7VyQebTWUD_0A1Z8OBDDJAJIB_mmLY',
    appId: '1:353926578262:android:f3d85268fa5d95284c7bf7',
    messagingSenderId: '353926578262',
    projectId: 'football-afe29',
    storageBucket: 'football-afe29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTWZec2MLLL6KsUZd4l5wSDN0ttkITcg',
    appId: '1:774337897957:ios:ba5da9e710c49d76cf3b0c',
    messagingSenderId: '774337897957',
    projectId: 'futsalapp2',
    storageBucket: 'futsalapp2.appspot.com',
    iosBundleId: 'com.example.futsalapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFaGOtVhLwB_Qimgzd1_zgd1jOU2ai4YY',
    appId: '1:353926578262:web:aeb9a5a81fc6f3264c7bf7',
    messagingSenderId: '353926578262',
    projectId: 'football-afe29',
    authDomain: 'football-afe29.firebaseapp.com',
    storageBucket: 'football-afe29.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQTWZec2MLLL6KsUZd4l5wSDN0ttkITcg',
    appId: '1:774337897957:ios:ba5da9e710c49d76cf3b0c',
    messagingSenderId: '774337897957',
    projectId: 'futsalapp2',
    storageBucket: 'futsalapp2.appspot.com',
    iosBundleId: 'com.example.futsalapp2',
  );

}