// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa1p76NcZ__LGfV-eCfi_j4FS8vyWXZOw',
    appId: '1:897354500756:web:bf0f67b0dec2ce48200281',
    messagingSenderId: '897354500756',
    projectId: 'futsal123-33644',
    authDomain: 'futsal123-33644.firebaseapp.com',
    storageBucket: 'futsal123-33644.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-bN0nBL7jl1ktdZQ2GTjyIF3xPmyx2g',
    appId: '1:897354500756:android:af78640703151e9d200281',
    messagingSenderId: '897354500756',
    projectId: 'futsal123-33644',
    storageBucket: 'futsal123-33644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1Y5s7_XLhwB1ibIJdwnKcrHk3DJK_f0',
    appId: '1:897354500756:ios:dee87e0f6908b8e2200281',
    messagingSenderId: '897354500756',
    projectId: 'futsal123-33644',
    storageBucket: 'futsal123-33644.appspot.com',
    iosBundleId: 'com.example.futsalapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1Y5s7_XLhwB1ibIJdwnKcrHk3DJK_f0',
    appId: '1:897354500756:ios:dee87e0f6908b8e2200281',
    messagingSenderId: '897354500756',
    projectId: 'futsal123-33644',
    storageBucket: 'futsal123-33644.appspot.com',
    iosBundleId: 'com.example.futsalapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa1p76NcZ__LGfV-eCfi_j4FS8vyWXZOw',
    appId: '1:897354500756:web:1e97b71b3e579093200281',
    messagingSenderId: '897354500756',
    projectId: 'futsal123-33644',
    authDomain: 'futsal123-33644.firebaseapp.com',
    storageBucket: 'futsal123-33644.appspot.com',
  );
}
